services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak-examples-multi-service-token-exchange
    ports:
      - "8881:8080"
      - "8781:8787"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DEBUG_PORT: "*:8787"
    volumes:
      - ./import:/opt/keycloak/data/import
    restart: on-failure
    healthcheck:
      test: [ 'CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)new java.net.URL(args[0]).openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://qks-tokenexchange-keycloak:8080/realms/dev' ]
      interval: 1s
      timeout: 10s
      retries: 30
    command:
      - start-dev
      - --import-realm
      - --log-level=INFO,org.keycloak.services.managers:debug,org.keycloak.authentication:debug,org.keycloak.events:debug
      - --features=preview
      - --debug
    networks:
      default:
        aliases:
          - keycloak-examples-multi-service-token-exchange
